# Generated by Django 3.0.8 on 2020-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0004_auto_20200722_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umr',
            name='role',
            field=models.CharField(choices=[('t', 'teacher'), ('s', 'student')], max_length=1),
        ),
    ]
