# Generated by Django 3.0.8 on 2020-07-27 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0007_auto_20200727_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='id',
            field=models.AutoField(auto_created=True, default=23, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='link',
            field=models.CharField(default=uuid.uuid4, max_length=300, null=True, unique=True),
        ),
    ]
