# Generated by Django 3.0.8 on 2020-07-27 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0011_auto_20200727_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.Quiz'),
        ),
        migrations.CreateModel(
            name='Quiz2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('begin', models.CharField(max_length=100, null=True)),
                ('end', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.Meeting')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.Quiz2'),
        ),
    ]
