# Generated by Django 3.0.8 on 2020-07-21 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0003_auto_20200722_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(default=uuid.uuid4, max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
