# Generated by Django 3.0.8 on 2020-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0005_auto_20200722_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='begin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
