# Generated by Django 3.0.8 on 2020-07-27 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0006_auto_20200727_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.CharField(default=uuid.uuid4, max_length=300, primary_key=True, serialize=False),
        ),
    ]
