# Generated by Django 3.0.8 on 2020-07-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0008_auto_20200727_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='link',
        ),
    ]
