# Generated by Django 3.0.8 on 2020-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0009_remove_quiz_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
