# Generated by Django 3.0.8 on 2020-07-27 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0010_quiz_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='link',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
