# Generated by Django 3.0.8 on 2020-07-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0013_remove_quiz_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz2',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.Quiz'),
        ),
        migrations.DeleteModel(
            name='Quiz2',
        ),
    ]
