# Generated by Django 3.0.8 on 2020-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingApp', '0014_auto_20200727_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
